version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      MONGO_URI: mongodb://mongo:27017/grafiles

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
